Repository ucsb-cs156-s25/proj-dining-s25-06, pull requests merged in 2025-05, with the labels that each got.

#33 Timothy - Removed Longitude and Latitude
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: 5

#37 Timothy - auto approve reviews for reviewers who put no comments
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
Labels: 10

#35 Timothy - Added individual endpoints for menu item and tests
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
Labels: 10

#38 Timothy - Applied transformation to each of the workflows that uses [OLD CODE] to [NEW CODE]
  .github/workflows/04-gh-pages-redeploy-part-2.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/53-chromatic-main-branch.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: 10, Merge Candidate-CI

#29 SJ - Implemented a Review Table
  frontend/src/App.js
  frontend/src/fixtures/reviewFixtures.js
  frontend/src/main/components/Review/ReviewTable.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/stories/components/Review/ReviewTable.stories.js
  frontend/src/stories/pages/MyReviews/MyReviewsIndexPage.stories.js
  frontend/src/tests/components/Review/ReviewTable.test.js
  frontend/src/tests/pages/MyReviews/MyReviewsIndexPage.test.js
Labels: 20

#42 yl - FEATURE: refresh table
  frontend/src/main/components/Alias/AliasTable.js
Labels: Ready-For-Staff

#43 yl - moderator page
  frontend/src/main/pages/Moderate.js
Labels: 5, Merge Candidate-CI

#48 rg - add moderator role backend VER2
  src/main/java/edu/ucsb/cs156/dining/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/main/java/edu/ucsb/cs156/dining/entities/User.java
  src/main/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptor.java
  src/main/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptorConfig.java
  src/main/resources/db/migration/changes/Users001-AddMod.json
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptorTests.java
  src/test/java/edu/ucsb/cs156/dining/testconfig/MockCurrentUserServiceImpl.java
Labels: 5, Merge Candidate-CI

#46 Aryan - form for creating review
  frontend/src/fixtures/reviewFixtures.js
  frontend/src/main/components/Review/ReviewForm.js
  frontend/src/stories/components/Review/ReviewForm.stories.js
  frontend/src/tests/components/Review/ReviewTests.test.js
Labels: 5
